version: "3"
services:
  mysqldb:
    container_name: mysqldb1
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER:root
      - MYSQL_PASSWORD:root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aymen5NIDS2BD
    volumes:
      - db_vol:/var/lib/mysqldb

  departement_app:
    build: ./
    image: aymen-5nids2-g0
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - mysqldb1


volumes:
  db_vol:
